#!/bin/bash

# apache example

# FOLDERS=". app app/templates static"
# TAIL_CMD="tail /var/log/apache2/error.log"
# RESTART_CMD="sudo service apache restart"

# docker-compose example

FOLDERS="."
TAIL_CMD="docker-compose logs --tail 20 playbot"
RESTART_CMD="docker-compose up -d --build playbot"

LAST_UPDATE_TIME=0
SLEEP_TIME=30
TAIL=`${TAIL_CMD}`

while true; do

    UPDATE=false
    for folder in ${FOLDERS}; do
        for file in $folder/{.,}*; do
            if [ ! -d "$file" ]; then
                LASTCHAR=`echo "$file" | rev | cut -c 1`

                if [[ "$LASTCHAR" =~ ^(\.|\*) ]] ; then
                    FILEMOD=0
                else
                    FILEMOD=`stat -c %Y $file`

                    if [ $LAST_UPDATE_TIME -eq 0 ]; then
                        LAST_UPDATE_TIME=$FILEMOD
                    fi

                    if [ $FILEMOD -gt $LAST_UPDATE_TIME ]; then
                        LAST_UPDATE_TIME=$FILEMOD
                        UPDATE=true
                        UPDATE_FILE=$file
                    fi

                fi
            fi
        done
    done

    if [ "$UPDATE" == "true" ]; then
        echo "*** restart due to $UPDATE_FILE changing"
        ${RESTART_CMD}
    fi

    NEW_TAIL=`${TAIL_CMD}`

    if [ "$TAIL" != "$NEW_TAIL" ] ; then
        ${TAIL_CMD}
        TAIL=${NEW_TAIL}
    else
        printf .
    fi

    sleep ${SLEEP_TIME}

done
